/** @type {import('../../src/lib/project-content.js').ProjectInput} */
export default {
  slug: "ford",
  title: "Ford Bronco",
  category: "Campaigns",
  role: "IMC Campaign",
  year: "2026",
  tags: ["Campaign", "Mockups", "Automotive"],
  summary: "Campaign system and vehicle presentation mockups built around Ford Bronco.",
  featured: true,
  assetDir: "Ford",
  cover: "Cover Slim.png",
  hero: "Project Desktop.png",
  devices: [
    { src: "Project Desktop.png", label: "Desktop" },
    { src: "Project Tab.png", label: "Tablet" },
  ],
  body: `An integrated campaign exploration for Ford Bronco — mockups, layout systems, and presentation frames for a rugged outdoor story.`,
  gallery: [
    { src: "1.png" },
    { src: "2.png" },
    { src: "3.png" },
    { src: "4.png" },
    { src: "5.png" },
    { src: "6.png" },
    { src: "7.png" },
    { src: "8.png" },
    { src: "9.png" },
    { src: "10.png" },
    { src: "11.png" },
    { src: "12.png" },
    { src: "13.png" },
    { src: "14.png" },
    { src: "15.png" },
    { src: "16.png" },
    { src: "17.png" },
    { src: "18.png" },
    { src: "19.png" },
  ],
};
