/** @type {import('../../src/lib/project-content.js').ProjectInput} */
export default {
  slug: "hypedocs",
  title: "HypeDocs",
  category: "Branding",
  role: "Brand Design",
  year: "2024",
  tags: ["Brand", "Guidelines", "Identity"],
  summary: "Brand system and guidelines for a documentation product — voice, color, and application.",
  featured: true,
  assetDir: "Hypedocs",
  cover: "Cover Slim.png",
  hero: "Project Desktop.png",
  devices: [
    { src: "Project Desktop.png", label: "Desktop" },
    { src: "Project Tab.png", label: "Tablet" },
  ],
  body: `HypeDocs needed a confident identity that still felt usable in dense product UI. The system covers logo, type, color, and a full brand guidelines deck.`,
  gallery: [
    { src: "Artboard 7.png" },
    { src: "HypeDocs BrandGuidelinesV2.2.png" },
    { src: "HypeDocs BrandGuidelinesV2.22.png" },
    { src: "HypeDocs BrandGuidelinesV2.23.png" },
    { src: "HypeDocs BrandGuidelinesV2.24.png" },
    { src: "HypeDocs BrandGuidelinesV2.25.png" },
    { src: "HypeDocs BrandGuidelinesV2.26.png" },
    { src: "HypeDocs BrandGuidelinesV2.27.png" },
    { src: "HypeDocs BrandGuidelinesV2.28.png" },
    { src: "HypeDocs BrandGuidelinesV2.29.png" },
    { src: "HypeDocs BrandGuidelinesV2.210.png" },
    { src: "HypeDocs BrandGuidelinesV2.211.png" },
    { src: "HypeDocs BrandGuidelinesV2.212.png" },
    { src: "HypeDocs BrandGuidelinesV2.213.png" },
    { src: "HypeDocs BrandGuidelinesV2.214.png" },
    { src: "HypeDocs BrandGuidelinesV2.215.png" },
    { src: "HypeDocs BrandGuidelinesV2.216.png" },
    { src: "HypeDocs BrandGuidelinesV2.217.png" },
    { src: "HypeDocs BrandGuidelinesV2.218.png" },
    { src: "HypeDocs BrandGuidelinesV2.219.png" },
    { src: "HypeDocs BrandGuidelinesV2.220.png" },
    { src: "HypeDocs BrandGuidelinesV2.221.png" },
    { src: "HypeDocs BrandGuidelinesV2.222.png" },
    { src: "HypeDocs BrandGuidelinesV2.223.png" },
    { src: "HypeDocs BrandGuidelinesV2.224.png" },
    { src: "HypeDocs BrandGuidelinesV2.225.png" },
    { src: "HypeDocs BrandGuidelinesV2.226.png" },
    { src: "HypeDocs BrandGuidelinesV2.227.png" },
    { src: "HypeDocs BrandGuidelinesV2.228.png" },
    { src: "HypeDocs BrandGuidelinesV2.229.png" },
    { src: "HypeDocs BrandGuidelinesV2.230.png" },
    { src: "HypeDocs BrandGuidelinesV2.231.png" },
    { src: "HypeDocs BrandGuidelinesV2.232.png" },
  ],
};
